// Generated by CoffeeScript 1.3.1
(function() {

  Ext.application({
    name: "Kada",
    controllers: ["notes"],
    views: ["notes_list_container"],
    launch: function() {
      var notes_list_container;
      notes_list_container = Ext.create("Kada.view.notes_list_container");
      Ext.Viewport.add(notes_list_container);
      return console.log("Load!");
    }
  });

}).call(this);
